### PR TITLE
[README] Minor typo fix

### PR DESCRIPTION
**Pull request by koshy1123**

### CODE REVIEW

**Comment by ryanfoxsquire** [comment]
thank you @koshy1123

**Comment by ryanfoxsquire** [comment]
@Trippl7777 I merged this but then it through a build error (see actions tab). The test must be broken, can you investigate?

**Comment by Trippl7777** [comment]
@ryanfoxsquire Ill take a look asap

**Comment by Trippl7777** [comment]
@ryanfoxsquire should be good to go now.

**Pull request merged**
